### ISSUE TITLE
how to produce cl column in the kmeans_10 file

### ISSUE THREAD

**Issue by yjiakang** [YulongNiu/MPIPZ_microbe-host_homeostasis#1]
Hi, congratulations on your article published in the nature plants. Thanks for code sharing. I am a little confused how is each gene clustered into different clusters? That is to say, how to produce cl column in the kmeans_10 file? Thanks in advance for any help.

**Comment by YulongNiu** [comment]
https://github.com/YulongNiu/MPIPZ_microbe-host_homeostasis/blob/d0b96ec5c384f42ae5df51fe80e84e82e181e236/RNA-Seq_scripts/script_cluster_1stadd.R#L198

Please check the code above.

**Comment by YulongNiu** [comment]
Dear colleague please also leave your name and affiliate.

**Comment by yjiakang** [comment]
Hi, I am Jiakang Yin from Huazhong agricultural university. Thanks for reply.
Best
Jk Yin

**Comment by yjiakang** [comment]
Sorry for disturbance again, could you guide me to the script for annotation of clusters? As shown in Fig. 3C.
Best
Jk Yin

**Comment by YulongNiu** [comment]
@yjiakang https://github.com/YulongNiu/MPIPZ_microbe-host_homeostasis/blob/master/RNA-Seq_scripts/script_replot_heatmap_1stadd.R
It is also indicated in the readme file as "script_replot_heatmap_1stadd.R for Col-0 heatmap plot."

**Comment by yjiakang** [comment]
Sorry, I mean the functional annotation of clusters. Thanks for your patience.

**Comment by YulongNiu** [comment]
@yjiakang https://github.com/YulongNiu/MPIPZ_microbe-host_homeostasis#16-go-enrichment
